# Site settings
title: "Naijav :: Client for Bara"
email: we@forfuture.co.ke
description: >
  Naijav is a Client Application for the Bara Transport Notification Service
  localized for public transport in Kenya.
baseurl: /naijav
url: http://dev.forfuture.co.ke
github_username:  forfuture-dev

# Build settings
markdown: kramdown
